### ISSUE TITLE
Uploading the SNES Controller Program to the Arduino Nano

### ISSUE THREAD

**Issue by matteog** [Zekfoo/gbaHD-AIO-Shield#1]
Ok so I just discovered something. I bought an off-brand Nano, and when I tried to upload the SNES controller program to it, I got an error. After a couple of seconds of searching I came across the Processor option under Tools in the Arduino suite.

I selected the Atmega328P (Old Bootloader) option, and then the program got flashed correctly. So I think what is happening is that Arduino defaults to the regular Atmega328P processor bootloader option, which I believe is powering the newer Nano Every.

This was on a Windows PC running version 1.8.18 of the Arduino suite.

**Comment by Zekfoo** [comment]
This is a known issue for some Nano clones, but it is not specific to the shield.
